spring:
  graphql:
    graphiql:
      enabled: true
      path: /graphiql
    path: /graphql
    schema:
      printer:
        enabled: true
      locations: classpath:graphql/

  config:
    import: optional:file:.env[.properties]

  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: ${POSTGRES_DRIVER}

  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: ${MONGODB_DATABASE}

  jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION}

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${GOOGLE_CLIENT_ID}
            clientSecret: ${GOOGLE_CLIENT_SECRET}
          scope: profile, email, openid


logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
#    org.springframework.security: Trace

management:
  endpoints:
    web:
      exposure:
        include: "*"


