db.url=jdbc:postgresql://localhost:5432/blogging_platform
db.username=postgres
db.password=kofi1yaw
db.driver=org.postgresql.Driver

mongodb.uri=mongodb://localhost:27017
mongodb.database=blog_db
mongodb.collection.comments=comments
